{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "token-boat.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "token-boat.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "token-boat.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
