/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TeamRouteImport } from './routes/team'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as OauthProviderRouteImport } from './routes/oauth.$provider'
import { Route as UserResetRouteImport } from './routes/user.reset'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthProviderRoute = OauthProviderRouteImport.update({
  id: '/oauth/$provider',
  path: '/oauth/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const UserResetRoute = UserResetRouteImport.update({
  id: '/user/reset',
  path: '/user/reset',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/getting-started': typeof GettingStartedRoute
  '/integration': typeof IntegrationRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/playground': typeof PlaygroundRoute
  '/preferences': typeof PreferencesRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/usage': typeof UsageRoute
  '/oauth/$provider': typeof OauthProviderRoute
  '/user/reset': typeof UserResetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/getting-started': typeof GettingStartedRoute
  '/integration': typeof IntegrationRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/playground': typeof PlaygroundRoute
  '/preferences': typeof PreferencesRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/usage': typeof UsageRoute
  '/oauth/$provider': typeof OauthProviderRoute
  '/user/reset': typeof UserResetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/alerts': typeof AlertsRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/getting-started': typeof GettingStartedRoute
  '/integration': typeof IntegrationRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/playground': typeof PlaygroundRoute
  '/preferences': typeof PreferencesRoute
  '/recharge': typeof RechargeRoute
  '/register': typeof RegisterRoute
  '/sign-in': typeof SignInRoute
  '/tasks': typeof TasksRoute
  '/team': typeof TeamRoute
  '/usage': typeof UsageRoute
  '/oauth/$provider': typeof OauthProviderRoute
  '/user/reset': typeof UserResetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activity'
    | '/alerts'
    | '/api-keys'
    | '/billing'
    | '/forgot-password'
    | '/getting-started'
    | '/integration'
    | '/logs'
    | '/models'
    | '/playground'
    | '/preferences'
    | '/recharge'
    | '/register'
    | '/sign-in'
    | '/tasks'
    | '/team'
    | '/usage'
    | '/oauth/$provider'
    | '/user/reset'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activity'
    | '/alerts'
    | '/api-keys'
    | '/billing'
    | '/forgot-password'
    | '/getting-started'
    | '/integration'
    | '/logs'
    | '/models'
    | '/playground'
    | '/preferences'
    | '/recharge'
    | '/register'
    | '/sign-in'
    | '/tasks'
    | '/team'
    | '/usage'
    | '/oauth/$provider'
    | '/user/reset'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activity'
    | '/alerts'
    | '/api-keys'
    | '/billing'
    | '/forgot-password'
    | '/getting-started'
    | '/integration'
    | '/logs'
    | '/models'
    | '/playground'
    | '/preferences'
    | '/recharge'
    | '/register'
    | '/sign-in'
    | '/tasks'
    | '/team'
    | '/usage'
    | '/oauth/$provider'
    | '/user/reset'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  AlertsRoute: typeof AlertsRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BillingRoute: typeof BillingRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GettingStartedRoute: typeof GettingStartedRoute
  IntegrationRoute: typeof IntegrationRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  PlaygroundRoute: typeof PlaygroundRoute
  PreferencesRoute: typeof PreferencesRoute
  RechargeRoute: typeof RechargeRoute
  RegisterRoute: typeof RegisterRoute
  SignInRoute: typeof SignInRoute
  TasksRoute: typeof TasksRoute
  TeamRoute: typeof TeamRoute
  UsageRoute: typeof UsageRoute
  OauthProviderRoute: typeof OauthProviderRoute
  UserResetRoute: typeof UserResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/$provider': {
      id: '/oauth/$provider'
      path: '/oauth/$provider'
      fullPath: '/oauth/$provider'
      preLoaderRoute: typeof OauthProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/reset': {
      id: '/user/reset'
      path: '/user/reset'
      fullPath: '/user/reset'
      preLoaderRoute: typeof UserResetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  AlertsRoute: AlertsRoute,
  ApiKeysRoute: ApiKeysRoute,
  BillingRoute: BillingRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GettingStartedRoute: GettingStartedRoute,
  IntegrationRoute: IntegrationRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  PlaygroundRoute: PlaygroundRoute,
  PreferencesRoute: PreferencesRoute,
  RechargeRoute: RechargeRoute,
  RegisterRoute: RegisterRoute,
  SignInRoute: SignInRoute,
  TasksRoute: TasksRoute,
  TeamRoute: TeamRoute,
  UsageRoute: UsageRoute,
  OauthProviderRoute: OauthProviderRoute,
  UserResetRoute: UserResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
